name: Android Kernel
on:
  workflow_dispatch:

jobs:

  buildkernel:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      

      - name: Display Python version
        run: python --version

      # Setup environment
      - name: Setup environment
        run: |   
            sudo apt-get update && sudo apt-get install -y \
             bc flex git ccache automake lzop bison gperf build-essential \
            zip curl zlib1g-dev g++-multilib python3-networkx libxml2-utils \
            bzip2 libbz2-dev squashfs-tools pngcrush schedtool dpkg-dev \
            liblz4-tool optipng libssl-dev python-is-python3 python3-virtualenv
            
            # Setup repo
            mkdir -p ~/.bin
            PATH="$HOME/.bin:$PATH"
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
            chmod a+rx ~/.bin/repo
            
      - name: Display Python version
        run: python --version

      # Set permissions
      - name: Set permissions
        run: chmod +x build_kernel.sh
        

      # Build kernel with debug mode
      - name: Build kernel
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHATID: ${{ secrets.TELEGRAM_CHATID }}
        run: |
          set -e
          bash -x build_kernel.sh

      # Package kernel
      - name: Package kernel
        run: |
          git clone https://github.com/Mohamedfullhd/AnyKernel3.git AnyKernel3
          rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
          if [[ -f out/arch/arm64/boot/Image.gz-dtb ]]; then
            cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
          elif [[ -f out/arch/arm64/boot/Image-dtb ]]; then
            cp out/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
          elif [[ -f out/arch/arm64/boot/Image.gz ]]; then
            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          elif [[ -f out/arch/arm64/boot/Image ]]; then
            cp out/arch/arm64/boot/Image AnyKernel3/Image
          fi
          if [[ -f out/arch/arm64/boot/dtbo.img ]]; then
            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          fi

      # Upload kernel artifact
      - name: Upload kernel to artifact
        uses: actions/upload-artifact@v4
        with:
          name: output_kernel
          path: AnyKernel3/*
